CREATE DATABASE databaseshop;
USE databaseshop;

CREATE TABLE THUONG_HIEU(
	ID INT NOT NULL,
	TENTH VARCHAR(20) NOT NULL,
	SLUG VARCHAR(20) NOT NULL
);
ALTER TABLE THUONG_HIEU ADD CONSTRAINT PK_THUONG_HIEU PRIMARY KEY (ID);


CREATE TABLE LOAI_SP(
	ID INT NOT NULL, 
	TEN VARCHAR(50)
);

ALTER TABLE LOAI_SP ADD CONSTRAINT PK_LOAI PRIMARY KEY (ID);

CREATE TABLE HINH_ANH(
	ID_SANPHAM INT NOT NULL,
	URL_ANH VARCHAR(300) NOT NULL
);

ALTER TABLE HINH_ANH ADD CONSTRAINT PK_ANH PRIMARY KEY (ID_SANPHAM, URL_ANH);

CREATE TABLE SL_SP(
	ID_SANPHAM INT NOT NULL,
	SO_LUONG INT NOT NULL,
	SL_DABAN INT NOT NULL
);

ALTER TABLE SL_SP ADD CONSTRAINT PK_SL_SP PRIMARY KEY (ID_SANPHAM, SO_LUONG);

CREATE TABLE CAU_HINH(
	ID_SANPHAM INT NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	TEN_TT VARCHAR(200) NOT NULL,
	GIA_TRI VARCHAR(500) NOT NULL
);

ALTER TABLE CAU_HINH ADD CONSTRAINT PK_CAU_HINH PRIMARY KEY (ID_SANPHAM, CODE);

CREATE TABLE SAN_PHAM(
	ID_SANPHAM INT NOT NULL,
	TEN_SP VARCHAR(500) NOT NULL,
	GIA_SP INT NOT NULL,
	GIA_KM INT NULL,
	MOTA_SP VARCHAR(1000) NULL,
	ID_THUONG_HIEU INT NOT NULL,
	ID_LOAI_SP INT NULL,
	NGAY_CAPNHAT DATE NOT NULL
);

CREATE TABLE GIO_HANG(
	ID_USER INT NOT NULL,
	ID_SP INT NOT NULL,
	SL_SP INT NOT NULL
);

CREATE TABLE DS_YEUTHICH(
	ID_USER INT NOT NULL,
	ID_SP INT NOT NULL
);

CREATE TABLE DON_HANG(
	ID_DH INT NOT NULL,
	ID_USER INT NOT NULL,
	STATUS TINYINT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_DATE DATETIME NOT NULL
);

CREATE TABLE CHITIET_DH(
	ID_DH INT NOT NULL,
	ID_SP INT NOT NULL,
	GIA INT NOT NULL,
	SL_SP INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_DATE DATETIME NOT NULL
);

CREATE TABLE TAI_KHOAN(
	ID_USER INT NOT NULL,
	USER_NAME VARCHAR(50) NULL,
	EMAIL VARCHAR(100) NOT NULL,
	TEN_ND VARCHAR(100) NOT NULL,
	MAT_KHAU VARCHAR(40) NOT NULL,
	TRANG_THAI VARCHAR(30) NOT NULL,
	QUYEN_HAN VARCHAR (50) NOT NULL,
	SDT VARCHAR(12) NULL,
	DIA_CHI VARCHAR(200) NULL,
	CREATE_DATE DATETIME NOT NULL
	
);


CREATE TABLE DANH_GIA_SP(
	ID_SP INT NOT NULL,
	ID_USER INT NOT NULL,
	MUC_DANHGIA INT NOT NULL,
	NOIDUNG_DG VARCHAR(200) NOT NULL,
	NGAY_DG DATETIME NOT NULL
);

ALTER TABLE DANH_GIA_SP ADD CONSTRAINT PK_DG_SP PRIMARY KEY (ID_SP, ID_USER);

ALTER TABLE TAI_KHOAN ADD CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (ID_USER);

ALTER TABLE CHITIET_DH ADD CONSTRAINT PK_CT_DH PRIMARY KEY (ID_DH, ID_SP);

ALTER TABLE DON_HANG ADD CONSTRAINT PK_DON_HANG PRIMARY KEY (ID_DH);

ALTER TABLE SAN_PHAM ADD CONSTRAINT PK_SAN_PHAM PRIMARY KEY (ID_SANPHAM);

ALTER TABLE SAN_PHAM ADD CONSTRAINT FK_TH_SP FOREIGN KEY (ID_THUONG_HIEU) REFERENCES THUONG_HIEU(ID);

ALTER TABLE SAN_PHAM ADD CONSTRAINT FK_LSP_SP FOREIGN KEY (ID_LOAI_SP) REFERENCES LOAI_SP(ID);

ALTER TABLE HINH_ANH ADD CONSTRAINT FK_SP_HA FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE CAU_HINH ADD CONSTRAINT FK_SP_CH FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE SL_SP ADD CONSTRAINT FK_SP_SL FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE GIO_HANG ADD CONSTRAINT PK_GIO_HANG PRIMARY KEY (ID_USER, ID_SP);

ALTER TABLE GIO_HANG ADD CONSTRAINT FK_SP_GH FOREIGN KEY (ID_SP) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE DS_YEUTHICH ADD CONSTRAINT FK_SP_YT FOREIGN KEY (ID_SP) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE CHITIET_DH ADD CONSTRAINT FK_SP_DH FOREIGN KEY (ID_SP) REFERENCES SAN_PHAM(ID_SANPHAM);

ALTER TABLE CHITIET_DH ADD CONSTRAINT FK_DH_CTDH FOREIGN KEY (ID_DH) REFERENCES DON_HANG(ID_DH);

ALTER TABLE GIO_HANG ADD CONSTRAINT FK_TK_GH FOREIGN KEY (ID_USER) REFERENCES TAI_KHOAN(ID_USER);

ALTER TABLE DS_YEUTHICH ADD CONSTRAINT FK_TK_YT FOREIGN KEY (ID_USER) REFERENCES TAI_KHOAN(ID_USER);

ALTER TABLE DON_HANG ADD CONSTRAINT FK_TK_DH FOREIGN KEY (ID_USER) REFERENCES TAI_KHOAN(ID_USER);

ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_TK_DG FOREIGN KEY (ID_USER) REFERENCES TAI_KHOAN(ID_USER);

ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_SP_DG FOREIGN KEY (ID_SP) REFERENCES SAN_PHAM(ID_SANPHAM);